#!/usr/bin/lua5.4
--
-- SPDX-FileCopyrightText: (c) 2026 Ring Zero Desenvolvimento de Software LTDA
-- SPDX-License-Identifier: MIT OR GPL-2.0-only
--

local lunatik = {
	device = "/dev/lunatik",
}

function lunatik.open(mode)
	return io.open(lunatik.device, mode)
end

function lunatik.loadstring(chunk)
	local loader <close> = assert(lunatik.open("r+"))
	loader:write(chunk)
end

function lunatik.result()
	local reader <close> = lunatik.open("r")
	return reader:read("a")
end

function lunatik.dostring(chunk)
	lunatik.loadstring(chunk)
	return lunatik.result()
end

local function readfile(path)
	local f <close> = assert(io.open(path, "rb"))
	return f:read("a")
end

local function bin2hex(s)
	return string.format(string.rep("%.2x", #s), string.unpack(string.rep("B", #s), s))
end

local function trim(script)
	return script:gsub("(%w+).lua", "%1")
end

local function gensecret()
	local f <close> = assert(io.open("/dev/urandom", "rb"))
	return bin2hex(f:read(32))
end

local script = arg[1]
local algo = arg[2] or "gcm(aes)"
if not script then
	io.stderr:write("usage: darken <script> [algo]\n")
	os.exit(false)
end

-- require dark module once at startup
lunatik.loadstring("dark = require('dark')")

local name = trim(script)
local secret_hex = gensecret()

local plaintext = readfile(script)
local pt_hex = bin2hex(plaintext)

local chunk = string.format(
	"return dark.encrypt('%s', '%s', '%s')",
	pt_hex, secret_hex, algo)
local result = lunatik.dostring(chunk)

local nonce_hex, ct_hex = string.match(result, "([^\t]+)\t([^\t]+)")
if not nonce_hex then
	error("encryption failed: " .. result)
end

local darken_path = name .. ".dark.lua"
local f <close> = assert(io.open(darken_path, "w"))
f:write(string.format(
	"-- darkened script generated by darken\n" ..
	"require(\"light\")\n" ..
	"local dark = require(\"dark\")\n" ..
	"local util = require(\"util\")\n" ..
	"return dark.run(util.hex2bin(\"%s\"), util.hex2bin(\"%s\"))\n",
	ct_hex, nonce_hex))

print("Darkened: " .. darken_path)
print("Secret:   " .. secret_hex)
